name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git clone https://github.com/migueldeicaza/esctest.git 

    - name: Xcode Mac Build
      #run: swift build -v
      run: xcodebuild -scheme MacTerminal -workspace SwiftTerm.xcworkspace

    - name: Swift Package Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
